Fixed 3 dead links in README.txt
homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum pull request #536
Opened 2022-09-02 05:21 UTC by luc-ass

Just a small fix to the README file: `.js` ➡️ `.ts`

This is not a functional implementation. No new release is needed.

2022-09-02 18:56 UTC, afharo requested changes
Thank you for the changes!! It's great to see folks care about the readme 🧡

I think the links need to be updated and, afaik, the default values of the goToX and goToY are not correct. Other than that, it looks great!

2022-09-02 18:56 UTC, afharo commented on README.md
> +  - [Fanspeed levels](./models/speedmodes.ts) adjustable via 3D Touch / Force Touch.
I think the link is still dead? Should it be?

```suggestion
  - [Fanspeed levels](./src/models/speedmodes.ts) adjustable via 3D Touch / Force Touch.
```

2022-09-02 18:56 UTC, afharo commented on README.md
> +  - [Watermode levels](./models/watermodes.ts) only when enabled in config, and the device supports it.
Same as my previous comment applies
```suggestion
  - [Watermode levels](./src/models/watermodes.ts) only when enabled in config, and the device supports it.
```

2022-09-02 18:56 UTC, afharo commented on README.md
> +| `goToX`               | `"where are you"`     | x-coordinate of the specified location
I believe the default value is 25000?

2022-09-02 18:56 UTC, afharo commented on README.md
> +1. Check the [./models/models.ts](./models/models.ts) file to see if your device is already in the explicit list.
Same as the previous comments. We need to nest it into src
```suggestion
1. Check the [models.ts](./src/models/models.ts) file to see if your device is already in the explicit list.
```

2022-09-03 07:30 UTC, luc-ass commented on README.md
> +| `goToX`               | `"where are you"`     | x-coordinate of the specified location
25500. corrected it.

2022-09-03 07:33 UTC, luc-ass commented
No idea why the checks fail…

2022-09-04 15:14 UTC, luc-ass commented
here we go

2022-09-04 16:03 UTC, afharo approved these changes
@luc-ass you rock!!

2022-09-04 16:03 UTC, merged